
//
// Files form save creation constants
//

export const SAVE_CREATION_RESET_STATE_FILES = 'SAVE_CREATION_RESET_STATE_FILES';
export const SAVE_CREATION_ADD_FILE = 'SAVE_CREATION_ADD_FILE';
export const SAVE_CREATION_ADD_ALL_FILES = 'SAVE_CREATION_ADD_ALL_FILES';
export const SAVE_CREATION_ADD_FILE_ERROR = 'SAVE_CREATION_ADD_FILE_ERROR';
export const SAVE_CREATION_CAN_ADD_FILE = 'SAVE_CREATION_CAN_ADD_FILE';
