//
// Save History Constants
//
// Follow this format:
//    export const YOUR_ACTION_CONSTANT = 'yourproject/YourContainer/YOUR_ACTION_CONSTANT';
//

export const GET_HISTORY_SAVES_BY_USER = 'SAM/SaveHistory/GET_HISTORY_SAVES_BY_USER';
export const SHOW_DELETION_SCHEDULED_SAVE_MODAL = 'SAM/SaveHistory/SHOW_DELETION_SCHEDULED_SAVE_MODAL';
export const SHOW_INSTANT_SAVE_MODAL = 'SAM/SaveHistory/SHOW_INSTANT_SAVE_MODAL';
export const SHOW_INSTANT_RESTORE_MODAL = 'SAM/SaveHistory/SHOW_INSTANT_RESTORE_MODAL';
export const INSTANT_RESTORE = 'SAM/SaveHistory/INSTANT_RESTORE';
export const RESET_RESTORE_STATE = 'SAM/SaveHistory/RESET_RESTORE_STATE';
export const DELETE_SCHEDULED_SAVE_INFO = 'SAM/SaveHistory/DELETE_SCHEDULED_SAVE_INFO';
