//
// Group name edit group constants
//

export const EDIT_GROUP_GROUP_NAME_CHANGE = 'EDIT_GROUP_GROUP_NAME_CHANGE';
export const EDIT_GROUP_RESET_STATE_GROUP_NAME = 'EDIT_GROUP_RESET_STATE_GROUP_NAME';
export const EDIT_GROUP_GROUP_NAME_ERROR = 'EDIT_GROUP_GROUP_NAME_ERROR';
