//
// Files form restore creation constants
//

export const RESTORE_CREATION_RESET_STATE_FILES = 'RESTORE_CREATION_RESET_STATE_FILES';
export const RESTORE_CREATION_LIST_FILES = 'RESTORE_CREATION_LIST_FILES';
export const RESTORE_CREATION_SELECTED_FILES = 'RESTORE_CREATION_SELECTED_FILES';
export const RESTORE_CREATION_FILES_ERROR = 'RESTORE_CREATION_FILES_ERROR';
