//
// Password confirmation form edit user constants
//

export const EDIT_USER_PASSWORD_CONFIRMATION_CHANGE = 'EDIT_USER_PASSWORD_CONFIRMATION_CHANGE';
export const EDIT_USER_RESET_STATE_PASSWORD_CONFIRMATION = 'EDIT_USER_RESET_STATE_PASSWORD_CONFIRMATION';
export const EDIT_USER_PASSWORD_CONFIRMATION_ERROR = 'EDIT_USER_PASSWORD_CONFIRMATION_ERROR';
