//
// Software Constants
//

export const SOFTWARE_USERS_GET_USERS = 'SOFTWARE_USERS_GET_USERS';
export const SOFTWARE_USERS_GET_USERS_OS = 'SOFTWARE_USERS_GET_USERS_OS';
export const SOFTWARE_USERS_REFRESH = 'SOFTWARE_USERS_REFRESH';
