//
// All users form create group constants
//

export const CREATE_GROUP_ADD_USERS_IN_GROUP = 'CREATE_GROUP_ADD_USERS_IN_GROUP';
export const CREATE_GROUP_UNSELECTED_USERS = 'CREATE_GROUP_UNSELECTED_USERS';
