//
// All users form notifications constants
//

export const NOTIFICATIONS_GET_USERS = 'NOTIFICATIONS_GET_USERS';
export const NOTIFICATIONS_PRE_SELECTED_USERS = 'NOTIFICATIONS_PRE_SELECTED_USERS';
export const NOTIFICATIONS_REMOVE_USERS = 'NOTIFICATIONS_REMOVE_USERS';
export const NOTIFICATIONS_RESET_STATE_ALL_USERS = 'NOTIFICATIONS_RESET_STATE_ALL_USERS';
