//
// Save Constants
//

export const GET_SAVES = 'GET_SAVES';
export const GET_USERS = 'GET_USERS';
export const SHOW_INSTANT_SAVE_MODAL = 'SHOW_INSTANT_SAVE_MODAL';
export const SHOW_INSTANT_RESTORE_MODAL = 'SHOW_INSTANT_RESTORE_MODAL';
export const RESET_RESTORE_STATE = 'RESET_RESTORE_STATE';
export const INSTANT_RESTORE = 'INSTANT_RESTORE';
