//
// User software deletion modal softwares by user constants
//

const SOFTWARES_BY_USER_SHOW_DELETE_SOFTWARE_MODAL = 'SOFTWARES_BY_USER_SHOW_DELETE_SOFTWARE_MODAL';
export default SOFTWARES_BY_USER_SHOW_DELETE_SOFTWARE_MODAL;
