//
// Title notifications constants
//

export const NOTIFICATIONS_TITLE_CHANGE = 'NOTIFICATIONS_TITLE_CHANGE';
export const NOTIFICATIONS_RESET_STATE_TITLE = 'NOTIFICATIONS_RESET_STATE_TITLE';
export const NOTIFICATIONS_TITLE_ERROR = 'NOTIFICATIONS_TITLE_ERROR';
