//
// All groups form notifications constants
//

export const NOTIFICATIONS_GET_GROUPS = 'NOTIFICATIONS_GET_GROUPS';
export const NOTIFICATIONS_PRE_SELECTED_GROUPS = 'NOTIFICATIONS_PRE_SELECTED_GROUPS';
export const NOTIFICATIONS_REMOVE_GROUPS = 'NOTIFICATIONS_REMOVE_GROUPS';
export const NOTIFICATIONS_RESET_STATE_ALL_GROUPS = 'NOTIFICATIONS_RESET_STATE_ALL_GROUPS';
