//
// Saves form restore creation constants
//

export const RESTORE_CREATION_RESET_STATE_SAVES = 'RESTORE_CREATION_RESET_STATE_SAVES';
export const RESTORE_CREATION_GET_HISTORY_SAVES_BY_USER_RESTORE = 'RESTORE_CREATION_GET_HISTORY_SAVES_BY_USER_RESTORE';
export const RESTORE_CREATION_SELECTED_SAVE = 'RESTORE_CREATION_SELECTED_SAVE';
export const RESTORE_CREATION_SAVE_ERROR = 'RESTORE_CREATION_SAVE_ERROR';
