//
// Save History Table Constants
//

export const SHOW_DELETION_SCHEDULED_SAVE_MODAL = 'SHOW_DELETION_SCHEDULED_SAVE_MODAL';
export const SHOW_INSTANT_SAVE_MODAL = 'SHOW_INSTANT_SAVE_MODAL';
export const SHOW_INSTANT_RESTORE_MODAL = 'SHOW_INSTANT_RESTORE_MODAL';
export const INSTANT_RESTORE = 'INSTANT_RESTORE';
export const RESET_RESTORE_STATE = 'RESET_RESTORE_STATE';
export const DELETE_SCHEDULED_SAVE_INFO = 'DELETE_SCHEDULED_SAVE_INFO';
