//
// Restore History instant restore modal Constants
//

const RESTORE_HISTORY_SHOW_INSTANT_RESTORE_MODAL = 'RESTORE_HISTORY_SHOW_INSTANT_RESTORE_MODAL';
export default RESTORE_HISTORY_SHOW_INSTANT_RESTORE_MODAL;
