//
// Group name create group constants
//

export const CREATE_GROUP_GROUP_NAME_CHANGE = 'CREATE_GROUP_GROUP_NAME_CHANGE';
export const CREATE_GROUP_RESET_STATE_GROUP_NAME = 'CREATE_GROUP_RESET_STATE_GROUP_NAME';
export const CREATE_GROUP_GROUP_NAME_ERROR = 'CREATE_GROUP_GROUP_NAME_ERROR';
