//
// Sofwares by user table constants
//

export const SOFTWARES_BY_USER_RESET_STATE_TABLE = 'SOFTWARES_BY_USER_RESET_STATE_TABLE';
export const SOFTWARES_BY_USER_SELECTED_SOFTWARES = 'SOFTWARES_BY_USER_SELECTED_SOFTWARES';
export const SOFTWARES_BY_USER_ALL_CHECKED = 'SOFTWARES_BY_USER_ALL_CHECKED';
export const SOFTWARES_BY_USER_SOFT_NAME = 'SOFTWARES_BY_USER_SOFT_NAME';
