//
// Description notifications constants
//

export const NOTIFICATIONS_DESCRIPTION_CHANGE = 'NOTIFICATIONS_DESCRIPTION_CHANGE';
export const NOTIFICATIONS_RESET_STATE_DESCRIPTION = 'NOTIFICATIONS_RESET_STATE_DESCRIPTION';
