//
// Persistence notifications constants
//

export const NOTIFICATIONS_PERSISTENCE_CHANGE = 'NOTIFICATIONS_PERSISTENCE_CHANGE';
export const NOTIFICATIONS_RESET_STATE_PERSISTENCE = 'NOTIFICATIONS_RESET_STATE_PERSISTENCE';
