//
// Date form Save Creation Constants
//

export const SAVE_CREATION_RESET_STATE_DATE = 'SAVE_CREATION_RESET_STATE_DATE';
export const SAVE_CREATION_DATE = 'SAVE_CREATION_DATE';
export const SAVE_CREATION_DATE_ERROR = 'SAVE_CREATION_DATE_ERROR';
export const SAVE_CREATION_DATE_DISABLED = 'SAVE_CREATION_DATE_DISABLED';
