//
// App constants
//

export const APP_SET_USER_INFO = 'APP_SET_USER_INFO';
export const APP_SET_APP_LOADING_STATE = 'APP_SET_APP_LOADING_STATE';
export const APP_SET_APP_REDIRECT_STATE = 'APP_SET_APP_REDIRECT_STATE';
