//
// Password form create user constants
//

export const CREATE_USER_PASSWORD_CHANGE = 'CREATE_USER_PASSWORD_CHANGE';
export const CREATE_USER_RESET_STATE_PASSWORD = 'CREATE_USER_RESET_STATE_PASSWORD';
export const CREATE_USER_PASSWORD_ERROR = 'CREATE_USER_PASSWORD_ERROR';
