//
// Users form Save Creation Constants
//

export const SAVE_CREATION_RESET_STATE_USERS = 'SAVE_CREATION_RESET_STATE_USERS';
export const SAVE_CREATION_LIST_USERS = 'SAVE_CREATION_LIST_USERS';
export const SAVE_CREATION_LIST_USERS_ERROR = 'SAVE_CREATION_LIST_USERS_ERROR';
