//
// Instant save delation modal save history page Constants
//

export const SAVE_HISTORY_SHOW_DELETION_SCHEDULED_SAVE_MODAL = 'SAVE_HISTORY_SHOW_DELETION_SCHEDULED_SAVE_MODAL';
export const SAVE_HISTORY_DELETE_SCHEDULED_SAVE_INFO = 'SAVE_HISTORY_DELETE_SCHEDULED_SAVE_INFO';
