//
// Password confirmation form create user constants
//

export const PASSWORD_CONFIRMATION_CHANGE = 'PASSWORD_CONFIRMATION_CHANGE';
export const RESET_STATE_PASSWORD_CONFIRMATION = 'RESET_STATE_PASSWORD_CONFIRMATION';
export const PASSWORD_CONFIRMATION_ERROR = 'PASSWORD_CONFIRMATION_ERROR';
