//
// Password confirmation form create user constants
//

export const CREATE_USER_PASSWORD_CONFIRMATION_CHANGE = 'CREATE_USER_PASSWORD_CONFIRMATION_CHANGE';
export const CREATE_USER_RESET_STATE_PASSWORD_CONFIRMATION = 'CREATE_USER_RESET_STATE_PASSWORD_CONFIRMATION';
export const CREATE_USER_PASSWORD_CONFIRMATION_ERROR = 'CREATE_USER_PASSWORD_CONFIRMATION_ERROR';
