//
// Migration history filters constants
//

export const MIGRATION_HISTORY_STATUS_CREATE_POPUP = 'MIGRATION_HISTORY_STATUS_CREATE_POPUP';
export const MIGRATION_HISTORY_GET_ALL_IMAGES = 'MIGRATION_HISTORY_GET_ALL_IMAGES';
export const MIGRATION_HISTORY_GET_ALL_USERS = 'MIGRATION_HISTORY_GET_ALL_USERS';
export const MIGRATION_HISTORY_CREATE_SET_USER = 'MIGRATION_HISTORY_CREATE_SET_USER';
export const MIGRATION_HISTORY_CREATE_SET_IMAGE = 'MIGRATION_HISTORY_CREATE_SET_IMAGE';
export const MIGRATION_HISTORY_CREATE_SET_DATE = 'MIGRATION_HISTORY_CREATE_SET_DATE';
export const MIGRATION_HISTORY_CREATE_SET_TIME = 'MIGRATION_HISTORY_CREATE_SET_TIME';
