//
// Frequency form Save Creation Constants
//

export const SAVE_CREATION_RESET_STATE_FREQUENCY = 'SAVE_CREATION_RESET_STATE_FREQUENCY';
export const SAVE_CREATION_FREQUENCY = 'SAVE_CREATION_FREQUENCY';
export const SAVE_CREATION_FREQUENCY_ERROR = 'SAVE_CREATION_FREQUENCY_ERROR';
export const SAVE_CREATION_FREQUENCY_DISABLED = 'SAVE_CREATION_FREQUENCY_DISABLED';
