//
// Password form edit user constants
//

export const EDIT_USER_PASSWORD_CHANGE = 'EDIT_USER_PASSWORD_CHANGE';
export const EDIT_USER_RESET_STATE_PASSWORD = 'EDIT_USER_RESET_STATE_PASSWORD';
export const EDIT_USER_PASSWORD_ERROR = 'EDIT_USER_PASSWORD_ERROR';
