//
// Persistance notifications constants
//

export const NOTIFICATIONS_PERSISTANCE_CHANGE = 'NOTIFICATIONS_PERSISTANCE_CHANGE';
export const NOTIFICATIONS_RESET_STATE_PERSISTANCE = 'NOTIFICATIONS_RESET_STATE_PERSISTANCE';
