//
// Dashboard constants
//

export const DASHBOARD_GET_SAVE_NUMBER = 'DASHBOARD_GET_SAVE_NUMBER';
export const DASHBOARD_GET_RESTORE_NUMBER = 'DASHBOARD_GET_RESTORE_NUMBER';
export const DASHBOARD_GET_DEAMON_USER_CONNECTED = 'DASHBOARD_GET_DEAMON_USER_CONNECTED';
