//
// Username form create user constants
//

export const CREATE_USER_USERNAME_CHANGE = 'CREATE_USER_USERNAME_CHANGE';
export const CREATE_USER_RESET_STATE_USERNAME = 'CREATE_USER_RESET_STATE_USERNAME';
export const CREATE_USER_USERNAME_ERROR = 'CREATE_USER_USERNAME_ERROR';
