//
// Grousp form edit user constants
//

export const EDIT_USER_GET_ALL_GROUPS = 'EDIT_USER_GET_ALL_GROUPS';
export const EDIT_USER_USER_GROUPS = 'EDIT_USER_USER_GROUPS';
export const EDIT_USER_RESET_STATE_GROUPS = 'EDIT_USER_RESET_STATE_GROUPS';
