//
// Migration history delete constants
//

export const MIGRATION_HISTORY_STATUS_DELETE_MODAL = 'MIGRATION_HISTORY_STATUS_DELETE_MODAL';
export const MIGRATION_HISTORY_SET_MIGRATION_TO_BE_DELETED = 'MIGRATION_HISTORY_SET_MIGRATION_TO_BE_DELETED';
