//
// Time form Save Creation Constants
//

export const SAVE_CREATION_RESET_STATE_TIME = 'SAVE_CREATION_RESET_STATE_TIME';
export const SAVE_CREATION_TIME = 'SAVE_CREATION_TIME';
export const SAVE_CREATION_TIME_ERROR = 'SAVE_CREATION_TIME_ERROR';
export const SAVE_CREATION_TIME_DISABLED = 'SAVE_CREATION_TIME_DISABLED';
