//
// Username form edit user constants
//

export const EDIT_USER_USERNAME_CHANGE = 'EDIT_USER_USERNAME_CHANGE';
export const EDIT_USER_RESET_STATE_USERNAME = 'EDIT_USER_RESET_STATE_USERNAME';
export const EDIT_USER_USERNAME_ERROR = 'EDIT_USER_USERNAME_ERROR';
