//
// Instant restore modal save page Constants
//

export const SAVE_SHOW_INSTANT_RESTORE_MODAL = 'SAVE_SHOW_INSTANT_RESTORE_MODAL';
export const SAVE_RESET_RESTORE_STATE = 'SAVE_RESET_RESTORE_STATE';
export const SAVE_INSTANT_RESTORE = 'SAVE_INSTANT_RESTORE';
