//
// Files modal form save creation constants
//

export const SAVE_CREATION_SHOW_ADD_FILE_MODAL = 'SAVE_CREATION_SHOW_ADD_FILE_MODAL';
export const SAVE_CREATION_INPUT_FILE_CHANGE = 'SAVE_CREATION_INPUT_FILE_CHANGE';
