
//
// Selected users form notifications constants
//

export const NOTIFICATIONS_ADD_USERS = 'NOTIFICATIONS_ADD_USERS';
export const NOTIFICATIONS_UNSELECTED_USERS = 'NOTIFICATIONS_UNSELECTED_USERS';
export const NOTIFICATIONS_REMOVE_SELECTED_USERS = 'NOTIFICATIONS_REMOVE_SELECTED_USERS';
export const NOTIFICATIONS_RESET_STATE_UNSELECTED_USERS = 'NOTIFICATIONS_RESET_STATE_UNSELECTED_USERS';
