//
// Instant restore modal save history page Constants
//

export const SAVE_HISTORY_SHOW_INSTANT_RESTORE_MODAL = 'SAVE_HISTORY_SHOW_INSTANT_RESTORE_MODAL';
export const SAVE_HISTORY_INSTANT_RESTORE = 'SAVE_HISTORY_INSTANT_RESTORE';
export const SAVE_HISTORY_RESET_RESTORE_STATE = 'SAVE_HISTORY_RESET_RESTORE_STATE';
