//
// Image Management constants
//

export const IMAGE_MANAGEMENT_SET_ADDIMAGE_VISIBILITY = 'IMAGE_MANAGEMENT_SET_ADDIMAGE_VISIBILITY';
export const IMAGE_MANAGEMENT_SET_FILENAME = 'IMAGE_MANAGEMENT_SET_FILENAME';
export const IMAGE_MANAGEMENT_SET_IMAGES = 'IMAGE_MANAGEMENT_SET_IMAGES';
export const IMAGE_MANAGEMENT_SET_NEW_FILES = 'IMAGE_MANAGEMENT_SET_NEW_FILES';
