//
// User software modal update all softwares by user constants
//

const SOFTWARES_BY_USER_SHOW_UPDATE_ALL_SOFTWARES_MODAL = 'SOFTWARES_BY_USER_SHOW_UPDATE_ALL_SOFTWARES_MODAL';
export default SOFTWARES_BY_USER_SHOW_UPDATE_ALL_SOFTWARES_MODAL;
