//
// User software modal add all softwares by user constants
//

const SOFTWARES_BY_USER_SHOW_ADD_ALL_SOFTWARES_MODAL = 'SOFTWARES_BY_USER_SHOW_ADD_ALL_SOFTWARES_MODAL';
export default SOFTWARES_BY_USER_SHOW_ADD_ALL_SOFTWARES_MODAL;
