//
// Searchbar sofwares by user constants
//

export const SOFTWARES_BY_USER_SEARCHBAR_CHANGE = 'SOFTWARES_BY_USER_SEARCHBAR_CHANGE';
export const SOFTWARES_BY_USER_SEARCHBAR_STATE = 'SOFTWARES_BY_USER_SEARCHBAR_STATE';
