//
// Sofwares by user constants
//

export const SOFTWARES_BY_USER_GET_SOFTWARES = 'SOFTWARES_BY_USER_GET_SOFTWARES';
export const SOFTWARES_BY_USER_USERNAME = 'SOFTWARES_BY_USER_USERNAME';
export const SOFTWARES_BY_USER_ADDITION_ALERT = 'SOFTWARES_BY_USER_ADDITION_ALERT';
export const SOFTWARES_BY_USER_UPDATE_ALERT = 'SOFTWARES_BY_USER_UPDATE_ALERT';
export const SOFTWARES_BY_USER_DELETION_ALERT = 'SOFTWARES_BY_USER_DELETION_ALERT';
export const SOFTWARES_BY_USER_RESET_ALERT = 'SOFTWARES_BY_USER_RESET_ALERT';
