//
// Sofwares by user constants
//

export const SOFTWARES_BY_USER_GET_SOFTWARES = 'SOFTWARES_BY_USER_GET_SOFTWARES';
export const SOFTWARES_BY_USER_USERNAME = 'SOFTWARES_BY_USER_USERNAME';
export const SOFTWARES_BY_USER_ALERT = 'SOFTWARES_BY_USER_ALERT';
export const SOFTWARES_BY_USER_RESET_ALERT = 'SOFTWARES_BY_USER_RESET_ALERT';
