//
// All users form create group constants
//

export const EDIT_GROUP_ADD_USERS_IN_GROUP = 'EDIT_GROUP_ADD_USERS_IN_GROUP';
export const EDIT_GROUP_UNSELECTED_USERS = 'EDIT_GROUP_UNSELECTED_USERS';
export const EDIT_GROUP_REMOVE_SELECTED_USERS = 'EDIT_GROUP_REMOVE_SELECTED_USERS';
