//
// Selected groups form notifications constants
//

export const NOTIFICATIONS_ADD_GROUPS = 'NOTIFICATIONS_ADD_GROUPS';
export const NOTIFICATIONS_UNSELECTED_GROUPS = 'NOTIFICATIONS_UNSELECTED_GROUPS';
export const NOTIFICATIONS_REMOVE_SELECTED_GROUPS = 'NOTIFICATIONS_REMOVE_SELECTED_GROUPS';
export const NOTIFICATIONS_RESET_STATE_UNSELECTED_GROUPS = 'NOTIFICATIONS_RESET_STATE_UNSELECTED_GROUPS';
export const NOTIFICATIONS_SELECTED_GROUPS_ERROR = 'NOTIFICATIONS_SELECTED_GROUPS_ERROR';
